<?php

/**
 * hook_menu
 */
function lookup_menu() {

  $items = array();
  $items['lookup/get/views'] = array(
      'title' => t('Lookup Load Views'),
      'description' => t('Lookup Views Page'),
      'page callback' => 'lookup_load_views',
      'type' => MENU_CALLBACK,
      'file' => 'lookup.load_views.inc',
      'access callback' => TRUE,
  );

  //Enable below to lines if you need a test demo.
//  module_load_include('inc', 'lookup', 'test/test_form_menu');
//  lookup_test_form_menu($items);

  return $items;
}

/**
 * hook_element_info_alter
 */
function lookup_element_info_alter(&$type) {
  //use the #pre_render of textfield to wrapper the browse link
  if (!isset($type['textfield']['#pre_render'])) {
    $type['textfield']['#pre_render'] = array();
  }
  array_unshift($type['textfield']['#pre_render'], 'lookup_textfield_pre_render_callback');
}

/**
 * Generate the lookup icon in element prerender callback
 * @param $element
 * @return $element
 */
function lookup_textfield_pre_render_callback($element) {
  if (isset($element['#type']) && $element['#type'] == 'textfield'
          && isset($element['#lookup']) && $element['#lookup'] == TRUE) {
    drupal_add_library('system', 'ui.dialog');
    $path = drupal_get_path('module', 'lookup');
    $lookup_img_link  = '<a href="#">
                            <img src="' . $path . '/img/search.png">
                        </a>';
    if(isset($element['#field_suffix']))
    {
      $element['#field_suffix'] = $element['#field_suffix'] . $lookup_img_link;
    }
    else
    {
      $element['#field_suffix'] = $lookup_img_link;
    }
  }
  return $element;
}
